### PR TITLE
Split the app in a participant and admin app

### PR DESCRIPTION
**Pull request by tahini**
** Breaking change for surveys **

This is a  big PR, which solves 3 issues: #51, #78 and #79. Each individual commit is standalone, but they break the application's functionalities until they are all there, so there are part of a single PR.

* It uses the participants table to link to the interviews instead of the users table (current users with interviews are copied to the participant table so current survey apps still work)
* There's a separate participant authentication model, which can use the same authentication methods as the user model, but uses the participants table instead of the users
* A participant app has a login page that uses the participant authentication model and can only display the participant's interview. It has no other rights.
* An admin app has a login page using the users authentication model. Users do not have an interview, their default home page displays their allowed pages.

When this PR is merged, all current surveys will need to be updated to use the latest evolution. See instructions in the individual commits for how to update

### CODE REVIEW

**Review by kaligrafy — APPROVED** [review]

**Comment by greenscientist** [comment]
This probably need a big update to the README of the app. Just having the configuration information in the commit message is not enough.

**Review by greenscientist — COMMENTED** [review]
Kind of wondering if we should add the login to the partipant table directly or to a side table instead.  (Unless the participant table is only used for login, then fine.)

**Comment by tahini** [comment]
@greenscientist you're right about the readme, totally forgot about it! 

As for the participant table, all those fields are for the login support of various methods (facebook, google, local login, anonymous, with confirmation, reset password, etc), mostly copy of the users table minus the user specific fields (is_admin, preferences, etc). Actually, the participant table is a side table for the sv_interviews.

**Comment by tahini** [comment]
@greenscientist just added the README

**Comment by tahini** [comment]
I'll merge so it can be used by projects right away. If anything is not clear or not completely working, we can fix later.

**Pull request merged**
