### PR TITLE
Fix sliders UI

### PR DESCRIPTION
**Pull request by samuel-duhaime**
# Pull request

## Justification
This is for fixing issues on MJ: 
https://github.com/chairemobilite/od_mj_2023/issues/275
https://github.com/chairemobilite/od_mj_2023/issues/281

## Description
Add space between question and slider
Remove max value and min value
Update cursor
Center current value
Update slider height for something bigger
Space between the slider and the label

## Screenshots
Before: 
image

After:
image

### CODE REVIEW

**Comment by samuel-duhaime** [comment]
Not sure, why I had commit [b41ffe3](https://github.com/chairemobilite/evolution/pull/604/commits/b41ffe36bdf774331cd196fe8f10dd22c78d925c) and commit [3463c70](https://github.com/chairemobilite/evolution/pull/604/commits/3463c70e907541206425aec05785ed23d84e9aa3) in this pull request...

**Comment by tahini** [comment]
You merged instead of rebase on the main branch. Just pull the main branch, then rebase this one on it and you should have only the last commit

**Review by tahini — CHANGES_REQUESTED** [review]
Very nice! The screenshots look convincing. Did you try on many screen sizes? With mouse and finger?

Please rebase on latest main to have only one commit in the PR.

I will let @kaligrafy review the css and give the final approval.

**Review by kaligrafy — APPROVED** [review]
Good but we will need to test on multiple platforms

**Review by tahini — APPROVED** [review]
C'est bon en ce qui me concerne! svp attendre l'approbation de @kaligrafy avant de merger

**Comment by tahini** [comment]
> C'est bon en ce qui me concerne! svp attendre l'approbation de @kaligrafy avant de merger

nvm il a déjà approuvé...

**Comment by samuel-duhaime** [comment]
Okay, I was able to have only the commit that I need (with some help from @tahini). 

I will open a new issue on MJ to test the InputRange on many platforms, but there should not be much problems.

**Pull request merged**
