### PR TITLE
adminExport: Add functionality to export interview logs to CSV

### LINKED ISSUE #721: Export interview logs in a parseable way
The `logs` column of the interview is a json array of json objects. It should be possible to export it to a csv, maybe exploding the array with one log per line associating a timestamp, interview_id and modified/deleted fields.

Then external tools can easily make sense of it.

### PR DESCRIPTION
**Pull request by tahini**
Commit message from the last commit:
    
fixes #721

This adds the functionality to export the interview logs to a CSV file.

There are 2 options for the export:

* `participantResponsesOnly` will export only the data for the fields in
  the `responses` field. Otherwise, all logs will be exported
* `withValues` will export the field as well as the value that has been
  set (or unset)

Both options can be combined.

In the export without values, there is one row per log entry in the
`logs` json field, with `timestamp`, `modifiedFields` and
`unsetFields` columns, along with the interview data (id, uuid,
is_valid, etc), sorted by interview ID, then timestamp.

In the export with values, the is one row per modified value, with a
`timestamp`, `field` and `value` columns, along with the interview data,
sorted by interview ID, then timestamp. Many entries may have the same
timestamp. Unset paths will have empty values.

The export is accessible through a task directly on the server, by
running `yarn node
`path/to/evolution-backend/lib/tasks/exportInterviewLogs.task.js`.

It is by design not made accessible through the UI, as currently, almost
everyone is admin in the system since we do not have a granular
permission. This contains potentially sensible data that should not be
exposed to everyone.

### CODE REVIEW

**Comment by tahini** [comment]
@samuel-duhaime  @kaligrafy Je mets ceci en draft pour tout de suite, pour voir s'il y aurait autre chose à ajouter à ça, d'autres formats désirés. Cet export propose 2 formats: avec ou sans les valeurs.

On pourrait ajouter des scripts plus tard pour processer ça, genre du python, ou direct du UI à partir du fichier. Bref, c'est ouvert à la discussion.

**Review by kaligrafy — APPROVED** [review]

**Comment by tahini** [comment]
J'ajouterais des paramètres à la task pour pouvoir exporter les logs d'une seule enquête par ID, pour du débogage ciblé mettons...

**Comment by tahini** [comment]
Added all --withValues, --participantResponsesOnly and --interviewId parameters to the task

**Comment by tahini** [comment]
@kaligrafy à re-reviewer, j'ai fait qq changements depuis ton approbation initiale

**Review by kaligrafy — APPROVED** [review]

**Comment by tahini** [comment]
Merging, to make it available in od_nationale in next release. We can update if there are issues or improvements to do

**Pull request merged**
