### PR TITLE
chore: fix yarn format for windows

### PR DESCRIPTION
**Pull request by samuel-duhaime**
chore: fix yarn format for windows
fixes: #196 

Comments: Can someone check if "yarn format" in evolution also work with Linux or Mac. I could only test with windows. I think, it should work.

### CODE REVIEW

**Review by tahini — CHANGES_REQUESTED** [review]
It works on Linux. Could you do a pull of the `main` branch first, then rebase your branch on it? We recently added a new evolution-interviewer module, which would also require this fix.

**Comment by samuel-duhaime** [comment]
> It works on Linux. Could you do a pull of the `main` branch first, then rebase your branch on it? We recently added a new evolution-interviewer module, which would also require this fix.

Yeah, I think it was already done. Current branch yarnFormatForWindows is up to date.

```
git checkout main
git pull origin main
git checkout yarnFormatForWindows
git rebase main
```

**Comment by tahini** [comment]
And what is your origin? is it upstream or your fork?

**Comment by samuel-duhaime** [comment]
En effet, l'origin était mon repo personnel avant (https://github.com/samuel-duhaime/evolution.git). J'ai fait quelques commandes pour essayer de corriger le tout. Je vais essayer de push à nouveau après.

```
git remote set-url origin https://github.com/chairemobilite/evolution.git
git remote -v

// Output
// origin  https://github.com/chairemobilite/evolution.git (fetch)
// origin  https://github.com/chairemobilite/evolution.git (push)
// upstream        https://github.com/chairemobilite/evolution.git (fetch)
// upstream        https://github.com/chairemobilite/evolution.git (push)
```

**Comment by tahini** [comment]
J'ai l'impression que le rebase ne s'est pas fait, tu as juste committé l'update du repo transition dans ton dernier commit, mais la base de ta branche est restée la même.

```
git checkout main
git pull upstream main
git checkout yarnFormatForWindows
git rebase main
```

Et là tu devrais voir le package evolution-interviewer

**Review by tahini — APPROVED** [review]

**Pull request merged**
