### PR TITLE
feat: add generateConditionals script for Generator

### PR DESCRIPTION
**Pull request by samuel-duhaime**
feat: add generateConditionals script for Generator

This is the documentation about Conditionals:

## Generate Conditionals

In your survey logic, conditionals play a key role in determining if the widget will appear or not. The table below outlines the fields used to define conditionals in Conditionals tab, along with an example and the corresponding TypeScript code.

### Conditionals Fields

| Field                        | Description                                 | Type                    |
| ---------------------------- | ------------------------------------------- | ----------------------- |
| conditional_name             | Name of the conditional                     | string                  |
| logical_operator             | Logical operator (optional)                 | && or \|\|              |
| path                         | Path to the responses object for comparison | string                  |
| [comparison_operator](#comp) | Operator for comparison                     | ===, ==, >, <, >= or <= |
| value                        | Value for the comparison                    | number or string        |
| [parentheses](#par)          | Parentheses (optional)                      | ( or )                  |

> <span id="comp">**Note:**</span> The `comparison_operator` field helps compare respondent responses with the specified value. It determines how the respondent's answer should be evaluated in the conditional logic. For example, `>=` signifies that the condition is true when path responses is greater than or equal to the value.

> <span id="par">**Note:**</span> The `parentheses` field is optional and allows you to add priority to the conditional logic by using opening and closing parentheses. This is useful for specifying the order in which conditions should be evaluated. For example, you can use parentheses to create complex conditions like `conditional1 || (conditional2 && conditional3)`, where `conditional2 && conditional3` is evaluated first due to the parentheses.

### Conditionals Example

In this example, we are creating a conditional named `hasDrivingLicenseConditional`. This conditional checks if the age of the person is 16 or older and if the person has a driving license. The table below shows the fields and their corresponding values for this conditional.

| conditional_name             | logical_operator | path                                   | comparison_operator | value | parentheses |
| ---------------------------- | ---------------- | -------------------------------------- | ------------------- | ----- | ----------- |
| hasDrivingLicenseConditional |                  | [${relativePath}](#rel).age            | >=                  | 16    |             |
| hasDrivingLicenseConditional | &&               | [${relativePath}](#rel).drivingLicense | ===                 | yes   |             |

> <span id="rel">**Note:**</span> `${relativePath}` in `path` is used to obtain the relative path within the same group, facilitating the reference to responses object that share a common parent or group with the current widget.

The corresponding TypeScript code for this conditional is shown below:

```typescript
// customConditionals.tsx
export const hasDrivingLicenseConditional: Conditional = (interview, path) => {
  const relativePath = path.substring(0, path.lastIndexOf(".")); // Remove the last key from the path
  return checkConditionals({
    interview,
    conditionals: [
      {
        path: `${relativePath}.age`,
        comparisonOperator: ">=",
        value: 16,
      },
      {
        logicalOperator: "&&",
        path: `${relativePath}.drivingLicense`,
        comparisonOperator: "===",
        value: "yes",
      },
    ],
  });
};
```

### CODE REVIEW

**Comment by tahini** [comment]
@samuel-duhaime This is a work in progress, but would it be possible to provide everything needed for someone to create a new example survey generated with the generator. You can start with one of the surveys you've worked on, after cleaning it up a bit.

It can be in the `generator` survey, or in `examples/demo_generated`, with complete instructions to generate and run the survey.

**Comment by samuel-duhaime** [comment]
> @samuel-duhaime This is a work in progress, but would it be possible to provide everything needed for someone to create a new example survey generated with the generator. You can start with one of the surveys you've worked on, after cleaning it up a bit.
> 
> It can be in the `generator` survey, or in `examples/demo_generated`, with complete instructions to generate and run the survey.

Oui, je peux faire ça assez facilement. Je viens d'ouvrir l'issue #356 pour cet effet.

**Comment by samuel-duhaime** [comment]
@tahini Okay, I got some change from your review.

- I added some helpers functions that I'm going to use again in other files.
- I separated the functions in generateConditionals
- I added NEWLINE
- I put error messages that we can catch
- I put notes to better describe the files
- I updated the documentation

**Comment by samuel-duhaime** [comment]
We are going to close, because it's now in pull request #364 .

**Pull request closed without merging**
