### PR TITLE
Remove path from InfoText of Generator

### PR DESCRIPTION
**Pull request by samuel-duhaime**
# Update Generator

## Description
Remove path from InputText of Generator. We don't need path for this input.

### CODE REVIEW

**Review by kaligrafy — CHANGES_REQUESTED** [review]
Can you explain why you removed the path attribute?

**Comment by samuel-duhaime** [comment]
> Can you explain why you removed the path attribute?

Yes. This is not InputText.tsx but Text.js from evolution-legacy. There is no path. It just a Label question with no answer. So the path is useless in this case.

image

**Comment by tahini** [comment]
> Yes. This is not InputText.tsx from evolution-frontend but Text.js from evolution-legacy. There is no path. It just a Label question with no answer. So the path is useless in this case.
> 
Then the commit message is wrong and probably the type's name too.

What we call Input* are input widgets, part of the Question component. Here, you are updating what should be the Text component, not the InputText.

You may fix it here, to more clearly differentiate the 2 concepts

**Comment by kaligrafy** [comment]
We should rename this InfoText if it is not an input

**Review by kaligrafy — APPROVED** [review]

**Pull request merged**
